name: Update Linguist Grammar

on:
  push:
    paths:
      - '.github/linguist/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-grammar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: .github/linguist
          
      - name: Install Dependencies
        working-directory: .github/linguist
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Validate Grammar
        working-directory: .github/linguist
        run: |
          bundle exec rake grammars:validate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore: update linguist grammar"
          title: "Update Linguist Grammar"
          body: "Updates the Objective-R grammar definitions for GitHub Linguist"
          branch: update-linguist-grammar
          base: main
