name: Update Linguist Grammar

on:
  push:
    paths:
      - '.github/linguist/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-grammar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: .github/linguist
          
      - name: Install Dependencies
        working-directory: .github/linguist
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Validate Grammar
        working-directory: .github/linguist
        run: |
          bundle exec rake grammars:validate

      - name: Commit Changes
        run: |
          git add .github/linguist
          git diff --staged --quiet || git commit -m "chore: update linguist grammar"
          git push
